#!/bin/sh

# IP_ADDR - this target IP address using CIDR notation:
# <target-ip>/<target-bitmask>
#
# For example:

echo "init started ..." | logger -s -t "rcS" -p user.info

/bin/mount -o remount,rw /

if [ -f /etc/debug.conf ]
then
      source /etc/debug.conf
fi

source /bin/delos_shell.sh
source /bin/user_gpio.sh
source /bin/leds_lib.sh
source /bin/dragon_shell.sh



echo "Mounting ..." | logger -s -t "rcS" -p user.info
/bin/mount -t tmpfs tmp /tmp
/bin/mount -t proc proc /proc
/bin/mount -t tmpfs dev /dev
/bin/mkdir -p /dev/shm /dev/pts
/bin/mount -t devpts devpts /dev/pts
/bin/mount -t sysfs sys /sys
/bin/mount -t debugfs none /sys/kernel/debug/

# Create /var in volatile fs
/bin/mount -t tmpfs tmp /var -o size=1M
for mydir in cache lock log run tmp lib; do
	mkdir -p /var/${mydir}
done

# Add a symbolic link for each I2C sensor
ln -s /dev/i2c-0 /dev/i2c-akm8963
ln -s /dev/i2c-0 /dev/i2c-mpu6050
ln -s /dev/i2c-0 /dev/i2c-ms5607

echo "Kernel setup ..." | logger -s -t "rcS" -p user.info

#don't allow overcommit (allocate more memory that the physical one)
echo 2 > /proc/sys/vm/overcommit_memory
echo 90 > /proc/sys/vm/overcommit_ratio

#in case of unaligned access print a message and send a SIGBUS
echo 5 > /proc/cpu/alignment

#reboot after 1s after a panic
echo 1 > /proc/sys/kernel/panic

#panic when an oops or BUG is encountered
#disable this for developer
echo 1 > /proc/sys/kernel/panic_on_oops

echo -1 > /proc/sys/kernel/sched_rt_runtime_us

echo "Hotplug mdev setup ..." | logger -s -t "rcS" -p user.info
echo "/sbin/mdev" > /proc/sys/kernel/hotplug
/sbin/mdev -s

/bin/mount -o remount,rw /

echo "Mounting NAND ..." | logger -s -t "rcS" -p user.info
/bin/mkdir -p /update
/bin/mkdir -p /factory
/bin/mount -a

/bin/mount -o remount,ro /


echo "Groups and priorities ..." | logger -s -t "rcS" -p user.info
#create groups of priorities
mkdir /dev/cpuctl
mount -t cgroup -ocpu none /dev/cpuctl
#mkdir /dev/cpuctl/video
# reserve most cpu for video tasks
#touch /dev/cpuctl/video/cpu.shares
#echo "2048" > /dev/cpuctl/video/cpu.shares
# group others
mkdir /dev/cpuctl/others
touch /dev/cpuctl/others/cpu.shares
echo "10000" >/dev/cpuctl/others/cpu.shares
touch /dev/cpuctl/others/tasks
for task in $(cat /dev/cpuctl/tasks)
do
    echo $task > /dev/cpuctl/others/tasks
done

model=$(read_hsis_model)

echo "LEDs ..." | logger -s -t "rcS" -p user.info
# Init all LEDs: RED ON, GREEN OFF, HEADLIGHT OFF
minidrone_leds _RR_

pcbrev=$(read_hsis_pcbrev)

echo "Mount virtual USB key ..." | logger -s -t "rcS" -p user.info
# Create mount point for the virtual USB key
mkdir -p ${DELOS_MOUNT_PATH}
# Make it read-only by default
chmod 400 ${DELOS_MOUNT_PATH}
# Create mount point for the virtual USB key debug
mkdir -p ${DELOS_DEBUG_MOUNT_PATH}
# Make it read-only by default
chmod 400 ${DELOS_DEBUG_MOUNT_PATH}

echo "Configuration files ..." | logger -s -t "rcS" -p user.info
# Be sure we have a config file
if [ ! -s /data/dragon.conf ]
then
    cp /etc/default-dragon.conf /data/dragon.conf
fi

if [ ! -s /data/system.conf ]
then
    cp /etc/default-system.conf /data/system.conf
fi

/bin/create_btconfig.sh

# Init the EtronTech USB<->Camera chip
echo "Etron setup ..." | logger -s -t "rcS" -p user.info
gpio_out HRESET_CAM 1
gpio_out USB_MUX_CMD 1

echo "Network setup ..." | logger -s -t "rcS" -p user.info
if [ -e /etc/hostname ]; then
    /bin/hostname -F /etc/hostname
fi
/sbin/ifconfig lo 127.0.0.1 up
/sbin/route add -net 127.0.0.0 netmask 255.0.0.0 lo

#
# Start permanent TCP/IP services
# Available during flight via BT or via USB
#
inetd

#
# Start telnet deamon
#
telnetd -l /bin/login.sh

echo "Motors initialisation ..." | logger -s -t "rcS" -p user.info
init_motors.sh &

modprobe uvcvideo

# Start UDev
echo "Hotplug udev setup ..." | logger -s -t "rcS" -p user.info
udevd.sh


# In the future this should depends on the version of qualcomm settings...
echo "Qualcomm management ..." | logger -s -t "rcS" -p user.info
(/bin/qualcomm_charger_set_params.sh)&

# Load the Ultrasound driver early, it fails otherwise
echo "Load ultrasound ..." | logger -s -t "rcS" -p user.info
modprobe ultra_snd

#
# Start Bluetooth
#
echo "Start Bluetooth ..." | logger -s -t "rcS" -p user.info
(BLEproxy $(cat /etc/BLEproxy.args 2>/dev/null) >/dev/null 2>/dev/null) &

#
# Start the main soft
#
#echo "Launching Dragon ..." | logger -s -t "rcS" -p user.info
#DRAGONSHELL_checkNstart_dragon -out2null &

/bin/usb_host.sh

echo "end init ..." | logger -s -t "rcS" -p user.info

